Repository journey-to-the-future/soolsoolsool-frontend, pull requests merged in 2022-10, with the labels that each got.

#48 UI/42 mypage layout
  src/App.js
  src/components/Layout/Layout.jsx
  src/components/MyPage/MyPageBottom.jsx
  src/components/MyPage/MyPageTop.jsx
  src/index.js
  src/pages/MyPage.jsx
Labels: ui

#50 49 Fix button
  src/components/Button/ExploreButton.css
  src/components/Button/ExploreButton.js
  src/components/Button/MainButton.js
  src/components/Header/Header.jsx
  src/components/InfiniteScroll/InfiniteScroll.css
  src/components/InfiniteScroll/InfiniteScroll.js
  src/components/SideBar/ExploreSideBar.js
  src/pages/ExplorePage.jsx
  src/pages/MainPage.jsx
Labels: feature

#52 Feature/add dockerfile
  Dockerfile
Labels: feature

#55 [ui] header footer fix
  src/components/Footer/Footer.jsx
  src/components/Header/Header.jsx
  yarn.lock
Labels: ui

#56 [ui] mypage update
  src/components/MyPage/MyPageBottom.jsx
  src/pages/MyPage.jsx
Labels: ui

#58 Explore Page UI 구성 및 기능 구현
  package-lock.json
  package.json
  src/api/axios.js
  src/components/Button/ExploreButton.js
  src/components/InfiniteScroll/InfiniteScroll.css
  src/components/InfiniteScroll/InfiniteScroll.js
  src/components/Post/Post.js
  src/components/SideBar/ExploreSideBar.js
  src/hooks/usePosts.js
  src/pages/ExplorePage.jsx
  yarn.lock
Labels: feature, ui

#60 탐색 페이지 Post 컴포넌트 UI 변경 및 필터 색상 변경
  src/api/axios.js
  src/components/Button/ExploreButton.js
  src/components/InfiniteScroll/InfiniteScroll.css
  src/components/InfiniteScroll/InfiniteScroll.js
  src/components/Post/Post.js
  src/components/SideBar/ExploreSideBar.js
  src/pages/ExplorePage.jsx
Labels: feature, ui

#64 [feature] product route with id
  src/App.js
  src/api/axios.js
  src/components/Post/Post.js
  src/components/Product/DetailImage.jsx
  src/components/Product/DetailMain.jsx
  src/components/Product/NameCard.jsx
  src/components/TastingNote/StrengthBar.jsx
  yarn.lock
Labels: feature

#65 Feature/61main page UI
  package-lock.json
  src/api/axios.js
  src/assets/seoul-nightlife.jpg
  src/components/Button/MainButton.js
  src/components/Card/MainCard.jsx
  src/components/Post/MainPost.js
  src/components/Post/Post.js
  src/components/Slick/Slick.jsx
  src/components/Slider/Slider.css
  src/components/Slider/Slider.jsx
  src/pages/ExplorePage.jsx
  src/pages/MainPage.jsx
Labels: feature, ui

#66 [feature] connect products(main, explore) & add notfound page
  src/App.js
  src/components/Post/MainPost.js
  src/components/Post/Post.js
  src/components/Product/DetailMain.jsx
  src/components/Product/NameCard.jsx
  src/components/Slick/Slick.jsx
  src/components/common/ScrollToTop.jsx
  src/index.js
  src/pages/NotFound.jsx
  yarn.lock
Labels: feature

#68 헤더 버튼 변경 및 판매자 페이지 추가
  package-lock.json
  package.json
  public/index.html
  public/logo.png
  src/App.js
  src/components/AppBar/SellerSearchBar.jsx
  src/components/Button/HeaderOptionsButton.jsx
  src/components/Header/Header.jsx
  src/components/Post/MainPost.js
  src/components/Post/Post.js
  src/components/Table/SellerTable.jsx
  src/pages/SellerPage.jsx
  yarn.lock
Labels: feature, ui

#70 헤더 UI 버튼 추가
  src/App.js
  src/components/Button/HeaderOptionsButton.jsx
  src/components/Header/Header.jsx
  src/components/InfiniteScroll/InfiniteScroll.js
  src/pages/MainPage.jsx
  src/pages/SellerPage.jsx
  yarn.lock
Labels: feature, ui

#71 [feature] 탐색페이지 버튼 활성화
  src/components/Button/ExploreButton.js
  src/components/Product/DetailMain.jsx
  src/components/SideBar/ExploreSideBar.js
  src/pages/ExplorePage.jsx
Labels: feature

#72 [feature] 위시리스트 버튼 상호작용 활성화, 로컬스토리지 id 값 저장
  src/components/Button/FavoriteButton.jsx
  src/components/MyPage/MyPageBottom.jsx
  src/components/Product/NameCard.jsx
Labels: feature
