Repository journey-to-the-future/soolsoolsool-frontend, pull requests merged in 2022-09, with the labels that each got.

#20 [ui] create login page layout
  package.json
  src/App.js
  src/assets/복순도가.png
  src/components/DetailMain/DetailMain.jsx
  src/components/DetailMain/DetailMain.module.css
  src/components/Login/MyFormHelperText.jsx
  src/components/UI/BasicRating.jsx
  src/index.js
  src/pages/DetailPage.jsx
  src/pages/LoginPage.jsx
  src/pages/MainPage.jsx
  src/pages/SoolDetail.jsx
  src/styles/Reset.jsx
  yarn.lock
Labels: ui

#25 [feature/ui] product detail - information, tasting note, review
  src/App.js
  src/components/Footer/Footer.jsx
  src/components/Modal/ReviewModal.jsx
  src/components/Product/DetailImage.jsx
  src/components/Product/DetailMain.jsx
  src/components/Product/NameCard.jsx
  src/components/Product/PriceCard.jsx
  src/components/Review/Review.jsx
  src/components/TastingNote/StrengthBar.jsx
  src/components/TastingNote/TastingSlider.jsx
  src/components/UI/BasicRating.jsx
  src/constants/userData.js
  src/index.js
  src/pages/DetailPage.jsx
  src/pages/LoginPage.jsx
  src/pages/SignUpPage.jsx
  src/reducers/userReducer.jsx
Labels: feature, ui

#26 [feature/ui] add main page slider
  src/components/Slider/Slider.css
  src/components/Slider/Slider.jsx
Labels: feature, ui

#28 [feature] add main page buttons
  src/components/Button/Buttons.jsx
Labels: feature, ui

#29 [feature] add main page card
  src/components/Card/MainCard.jsx
Labels: feature, ui

#31 [feature] add main page filter slider
  src/components/SliderBar/SliderBar.jsx
Labels: feature, ui

#33 [UI] 메인 페이지 UI 구성
  src/pages/MainPage.jsx
Labels: feature, ui

#35 [UI] add main page top section
  .gitignore
  README.md
  package-lock.json
  package.json
  postcss.config.js
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.js
  src/assets/soolsoolsool.png
  src/assets/복순도가.png
  src/components/Button/Buttons.jsx
  src/components/Card/MainCard.jsx
  src/components/Footer/Footer.jsx
  src/components/Header/Header.jsx
  src/components/Login/MyFormHelperText.jsx
  src/components/Slider/Slider.css
  src/components/Slider/Slider.jsx
  src/components/SliderBar/SliderBar.jsx
  src/components/UI/BasicRating.jsx
  src/index.css
  src/index.js
  src/pages/LoginPage.jsx
  src/pages/MainPage.jsx
  src/pages/SignUpPage.jsx
  src/section/MainSection/MainTopSection.jsx
  src/styles/Reset.jsx
  tailwind.config.js
  yarn.lock
Labels: ui

#37 Revert "[UI] add main page top section"
  .gitignore
  README.md
  package-lock.json
  package.json
  postcss.config.js
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.js
  src/assets/soolsoolsool.png
  src/assets/복순도가.png
  src/components/Button/Buttons.jsx
  src/components/Card/MainCard.jsx
  src/components/Footer/Footer.jsx
  src/components/Header/Header.jsx
  src/components/Login/MyFormHelperText.jsx
  src/components/Slider/Slider.css
  src/components/Slider/Slider.jsx
  src/components/SliderBar/SliderBar.jsx
  src/components/UI/BasicRating.jsx
  src/index.css
  src/index.js
  src/pages/LoginPage.jsx
  src/pages/MainPage.jsx
  src/pages/SignUpPage.jsx
  src/section/MainSection/MainTopSection.jsx
  src/styles/Reset.jsx
  tailwind.config.js
  yarn.lock
Labels: etc

#38 [feature] signup page validation check
  src/components/Login/MyFormHelperText.jsx
  src/pages/MainPage.jsx
  src/pages/SignUpPage.jsx
Labels: feature

#39 [feature] login page validation check
  src/pages/LoginPage.jsx
Labels: feature

#41 [feature] signup error message
  src/components/Login/MyFormHelperText.jsx
  src/pages/SignUpPage.jsx
Labels: feature

#46 [feature] add Infinite Scroll
  package-lock.json
  package.json
  src/App.js
  src/api/axios.js
  src/components/Header/Header.jsx
  src/components/InfiniteScroll/InfiniteScroll.css
  src/components/InfiniteScroll/InfiniteScroll.js
  src/components/Post/Post.js
  src/hooks/usePosts.js
  src/pages/ExplorePage.jsx
  yarn.lock
Labels: feature
